/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package telas;

import classes.Escola;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositorio.RepEscola;

/**
 *
 * @author Usuario
 */
public class JPEscola extends javax.swing.JDialog {
    
    RepEscola repescola = new RepEscola();
    Escola escola;
    public JPEscola(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencherTable();
    }
    
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JPEscola dialog = new JPEscola(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
public void preencherTable(){
    DefaultTableModel modelo = (DefaultTableModel)jTableListaES.getModel();
    modelo.setNumRows(0);
    
    for(Escola c : repescola.retornar()){
        modelo.addRow(new Object[]{
           //aqui vao ficar as colunas
            c.getInep(),
            c.getNome(),
            c.getCnpj(),
            c.getEndereco(),
            c.getAlunoid()
                
        });
    }
    
}
  public void JTablePesquisa(String valor){
        repescola = new RepEscola();
        DefaultTableModel modelo = (DefaultTableModel) jTableListaES.getModel();
        modelo.setNumRows(0);
        
        for(Escola c : repescola.pesquisa(valor)){
            modelo.addRow(new Object[]{
                //aqui vao ficar as colunas
                c.getInep(),
                c.getNome(),
                c.getAlunoid(),
                c.getEndereco(),
                c.getCnpj(),
                
            });
        }
        
    }
    /**
     * Creates new form JPEscola
     */
    public JPEscola() {
        initComponents();
        preencherTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSalvarES = new javax.swing.JButton();
        jButtonAlterarES = new javax.swing.JButton();
        jButtonExcluirES = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaES = new javax.swing.JTable();
        jTextFieldInep = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCnpj = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAlunoid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonNovoEs = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Cadastro Escolar");

        jButtonSalvarES.setText("Salvar");
        jButtonSalvarES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarESActionPerformed(evt);
            }
        });

        jButtonAlterarES.setText("Alterar");
        jButtonAlterarES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarESActionPerformed(evt);
            }
        });

        jButtonExcluirES.setText("Excluir");
        jButtonExcluirES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirESActionPerformed(evt);
            }
        });

        jTableListaES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Inep", "Nome", "Cnpj", "Endereço", "Aluno_id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaESMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaES);

        jTextFieldInep.setEditable(false);
        jTextFieldInep.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Inep:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("CNPJ:");

        jLabel5.setText("Endereço:");

        jTextFieldAlunoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlunoidActionPerformed(evt);
            }
        });

        jLabel6.setText("AlunoId:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Pesquisar:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonNovoEs.setText("Novo");
        jButtonNovoEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoEsActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonNovoEs)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonExcluirES)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonAlterarES)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonSalvarES)
                            .addGap(30, 30, 30))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextFieldInep, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonBuscar)))
                            .addGap(22, 22, 22)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldAlunoid, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAlunoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarES)
                    .addComponent(jButtonAlterarES)
                    .addComponent(jButtonExcluirES)
                    .addComponent(jButtonNovoEs)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarESActionPerformed
        // TODO add your handling code here:
        
        //Verificar campo obrigatorio
        
         if(jTextFieldNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor preencha o campo Nome");
            jTextFieldNome.requestFocus();
        }
        else if(jTextFieldCnpj.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor preencha o campo CNPJ");
            jTextFieldNome.requestFocus();
        }else{
            
            //criar o objeto
            Escola escola = new Escola();
            
            //preencha os dados no objeto
            escola.setNome(jTextFieldNome.getText());
            escola.setCnpj(jTextFieldCnpj.getText());
            escola.setEndereco(jTextFieldEndereco.getText());
            escola.setAlunoid(jTextFieldAlunoid.getText());
            
            //Se o codigo for Vazio de um INSERT
            if(jTextFieldInep.getText().equals("")){
                //inserir no banco de dados
                if(repescola.inserir(escola)==true){
                JOptionPane.showMessageDialog(null, "Executado com sucesso");
                limparCampos();
                preencherTable();
            }else{
                    JOptionPane.showMessageDialog(null,"Falha ao executar");
            }        
            }else{
                //se o código existir então é um update
            escola.setInep(Integer.parseInt(jTextFieldInep.getText()));
            //chamamos o método para alterar os dados
            if(repescola.atualizar(escola)==true){
                JOptionPane.showMessageDialog(null,"Executado com Sucesso");
                limparCampos();
                preencherTable();
                 }else{
                JOptionPane.showMessageDialog(null,"Falha ao Executar");
            }
            
            }
            
        }
    }//GEN-LAST:event_jButtonSalvarESActionPerformed

    private void jTableListaESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaESMouseClicked
        // TODO add your handling code here:
        if(jTableListaES.getSelectedRow() != - 1){
            jTextFieldInep.setText(jTableListaES.getValueAt(jTableListaES.getSelectedRow(), 0).toString());
             jTextFieldNome.setText(jTableListaES.getValueAt(jTableListaES.getSelectedRow(), 1).toString());
             jTextFieldCnpj.setText(jTableListaES.getValueAt(jTableListaES.getSelectedRow(), 2).toString());
             jTextFieldEndereco.setText(jTableListaES.getValueAt(jTableListaES.getSelectedRow(), 3).toString());
             jTextFieldAlunoid.setText(jTableListaES.getValueAt(jTableListaES.getSelectedRow(), 4).toString());
        
        }
    }//GEN-LAST:event_jTableListaESMouseClicked

    private void jButtonNovoEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoEsActionPerformed
        // TODO add your handling code here:
        
        zerarCampos();
        habilitaCampos(true);
        jTextFieldNome.requestFocus();
    }//GEN-LAST:event_jButtonNovoEsActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        zerarCampos();
        habilitaCampos(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAlterarESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarESActionPerformed
        // TODO add your handling code here:
         habilitaCampos(true);
        jTextFieldNome.requestFocus();
    }//GEN-LAST:event_jButtonAlterarESActionPerformed

    private void jButtonExcluirESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirESActionPerformed
        // TODO add your handling code here:
        
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir","Aviso", JOptionPane.YES_NO_OPTION);
        
        if (resposta == JOptionPane.YES_OPTION){
            //Usuário clicou em Sim 
            repescola.excluir(Integer.parseInt(jTextFieldInep.getText()));
            preencherTable();
        }else  if(resposta == JOptionPane.NO_OPTION){
             //Usuário clicou em não
        }
       
    }//GEN-LAST:event_jButtonExcluirESActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        JTablePesquisa(jTextFieldPesquisar.getText());
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextFieldAlunoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlunoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlunoidActionPerformed
        public void limparCampos(){
            jTextFieldInep.setText("");
            jTextFieldNome.setText("");
            jTextFieldCnpj.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldAlunoid.setText("");
           
       }
        
         public void habilitaCampos(boolean valor){
        
        jTextFieldNome.setEnabled(valor);
        jTextFieldCnpj.setEnabled(valor);
        jTextFieldEndereco.setEnabled(valor);
        jTextFieldAlunoid.setEnabled(valor);
       
    }
    
     public void zerarCampos(){
        jTextFieldInep.setText("");
        jTextFieldNome.setText("");
        jTextFieldCnpj.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldAlunoid.setText("");
       
    }
                

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarES;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluirES;
    private javax.swing.JButton jButtonNovoEs;
    private javax.swing.JButton jButtonSalvarES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaES;
    private javax.swing.JTextField jTextFieldAlunoid;
    private javax.swing.JTextField jTextFieldCnpj;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldInep;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
